"""empty message

Revision ID: 331060b4db12
Revises: e06e9b2fe02b
Create Date: 2024-03-15 21:16:35.221073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331060b4db12'
down_revision = 'e06e9b2fe02b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
